#!/bin/sh

# Получаем список изменённых файлов
changed_files=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

# Проверяем, есть ли среди них файлы из frontend/
frontend_files=$(echo "$changed_files" | grep '^frontend/' | sed 's/^frontend\///')

# Если нет изменённых файлов из frontend/ — пропускаем хук
if [ -z "$frontend_files" ]; then
    exit 0
fi

# Переходим в frontend/
cd frontend

# Запускаем prettier для файлов из frontend/
echo "$frontend_files" | grep -E '\.(html|js|jsx|ts|tsx|css|scss|json)$' | xargs ./node_modules/.bin/prettier --write

# Индексируем изменённые файлы из frontend/
echo "$frontend_files" | xargs git add

exit 0