#!/bin/sh

# Получаем список изменённых файлов
changed_files=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

# Проверяем, есть ли среди них файлы из frontend/
frontend_files=$(echo "$changed_files" | grep '^frontend/')

# Если нет изменённых файлов из frontend/ — пропускаем хук
if [ -z "$frontend_files" ]; then
    echo "No frontend files changed. Skipping frontend pre-commit hook."
    exit 0
fi

echo "Running frontend pre-commit hook..."

# Переходим во фронтенд-папку (если ещё не в ней)
if [[ "$(git rev-parse --show-prefix)" != "frontend/" ]]; then
    cd frontend || exit
fi

# Prettify all selected files
echo "$frontend_files" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$frontend_files" | xargs git add

# Возвращаемся в исходную директорию (если переходили)
if [[ "$(git rev-parse --show-prefix)" != "frontend/" ]]; then
    cd -
fi

exit 0


#----------------

# FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
# [ -z "$FILES" ] && exit 0

# # Prettify all selected files
# echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# # Add back the modified/prettified files to staging
# echo "$FILES" | xargs git add

# exit 0